// Generated by CoffeeScript 1.10.0
(function() {
  var ax12, imu, ref, sequencer, toolbox;

  ref = require('walkingdriver'), imu = ref.imu, toolbox = ref.toolbox, ax12 = ref.ax12;

  sequencer = require('./sequence');

  module.exports = (function(_this) {
    return function() {
      var result;
      imu.init();
      toolbox.init();
      ax12.init(115200);
      setInterval((function() {}), 10000);
      result = {
        ax12: require('./ax12')(ax12),
        heading: imu.heading,
        pitch: imu.pitch,
        roll: imu.roll,
        motorBattery: toolbox.motorPowerLevel,
        logicBattery: toolbox.logicPowerLevel,
        PMW: toolbox.PWM,
        LED: toolbox.LED,
        button: toolbox.button,
        sequence: function() {
          return sequencer(result);
        }
      };
      return result;
    };
  })(this);

}).call(this);
